// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          int32            `json:"id"`
	UserID      int32            `json:"user_id"`
	Status      string           `json:"status"`
	TotalAmount int32            `json:"total_amount"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type OrderProduct struct {
	ID        int32            `json:"id"`
	OrderID   int32            `json:"order_id"`
	ProductID int32            `json:"product_id"`
	Quantity  int32            `json:"quantity"`
	Price     int32            `json:"price"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
