// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderProduct(ctx context.Context, arg CreateOrderProductParams) (OrderProduct, error)
	GetOrderByID(ctx context.Context, id int32) (Order, error)
	GetOrderProductsByOrderID(ctx context.Context, orderID int32) ([]OrderProduct, error)
	GetOrderWithProducts(ctx context.Context, id int32) (GetOrderWithProductsRow, error)
	GetOrdersByUserID(ctx context.Context, arg GetOrdersByUserIDParams) ([]Order, error)
	GetOrdersByUserIDCount(ctx context.Context, userID int32) (int64, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
