// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: services/order-service.proto

package services

import (
	order "order-service/go-proto/modules/order"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_order_service_proto protoreflect.FileDescriptor

const file_services_order_service_proto_rawDesc = "" +
	"\n" +
	"\x1cservices/order-service.proto\x12\bservices\x1a\x13modules/order.proto2\xe7\x01\n" +
	"\x10OrderGRPCService\x12D\n" +
	"\vcreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12;\n" +
	"\bgetOrder\x12\x16.order.GetOrderRequest\x1a\x17.order.GetOrderResponse\x12P\n" +
	"\x0fgetOrdersByUser\x12\x1d.order.GetOrdersByUserRequest\x1a\x1e.order.GetOrdersByUserResponseB\x13Z\x11go-proto/servicesb\x06proto3"

var file_services_order_service_proto_goTypes = []any{
	(*order.CreateOrderRequest)(nil),      // 0: order.CreateOrderRequest
	(*order.GetOrderRequest)(nil),         // 1: order.GetOrderRequest
	(*order.GetOrdersByUserRequest)(nil),  // 2: order.GetOrdersByUserRequest
	(*order.CreateOrderResponse)(nil),     // 3: order.CreateOrderResponse
	(*order.GetOrderResponse)(nil),        // 4: order.GetOrderResponse
	(*order.GetOrdersByUserResponse)(nil), // 5: order.GetOrdersByUserResponse
}
var file_services_order_service_proto_depIdxs = []int32{
	0, // 0: services.OrderGRPCService.createOrder:input_type -> order.CreateOrderRequest
	1, // 1: services.OrderGRPCService.getOrder:input_type -> order.GetOrderRequest
	2, // 2: services.OrderGRPCService.getOrdersByUser:input_type -> order.GetOrdersByUserRequest
	3, // 3: services.OrderGRPCService.createOrder:output_type -> order.CreateOrderResponse
	4, // 4: services.OrderGRPCService.getOrder:output_type -> order.GetOrderResponse
	5, // 5: services.OrderGRPCService.getOrdersByUser:output_type -> order.GetOrdersByUserResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_order_service_proto_init() }
func file_services_order_service_proto_init() {
	if File_services_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_order_service_proto_rawDesc), len(file_services_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_order_service_proto_goTypes,
		DependencyIndexes: file_services_order_service_proto_depIdxs,
	}.Build()
	File_services_order_service_proto = out.File
	file_services_order_service_proto_goTypes = nil
	file_services_order_service_proto_depIdxs = nil
}
