// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: services/order-service.proto

package services_order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	modules_order "order-service/go-proto/proto/modules.order"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderGRPCService_CreateOrder_FullMethodName     = "/services.order.OrderGRPCService/createOrder"
	OrderGRPCService_GetOrder_FullMethodName        = "/services.order.OrderGRPCService/getOrder"
	OrderGRPCService_GetOrdersByUser_FullMethodName = "/services.order.OrderGRPCService/getOrdersByUser"
)

// OrderGRPCServiceClient is the client API for OrderGRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderGRPCServiceClient interface {
	CreateOrder(ctx context.Context, in *modules_order.CreateOrderRequest, opts ...grpc.CallOption) (*modules_order.CreateOrderResponse, error)
	GetOrder(ctx context.Context, in *modules_order.GetOrderRequest, opts ...grpc.CallOption) (*modules_order.GetOrderResponse, error)
	GetOrdersByUser(ctx context.Context, in *modules_order.GetOrdersByUserRequest, opts ...grpc.CallOption) (*modules_order.GetOrdersByUserResponse, error)
}

type orderGRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderGRPCServiceClient(cc grpc.ClientConnInterface) OrderGRPCServiceClient {
	return &orderGRPCServiceClient{cc}
}

func (c *orderGRPCServiceClient) CreateOrder(ctx context.Context, in *modules_order.CreateOrderRequest, opts ...grpc.CallOption) (*modules_order.CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(modules_order.CreateOrderResponse)
	err := c.cc.Invoke(ctx, OrderGRPCService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderGRPCServiceClient) GetOrder(ctx context.Context, in *modules_order.GetOrderRequest, opts ...grpc.CallOption) (*modules_order.GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(modules_order.GetOrderResponse)
	err := c.cc.Invoke(ctx, OrderGRPCService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderGRPCServiceClient) GetOrdersByUser(ctx context.Context, in *modules_order.GetOrdersByUserRequest, opts ...grpc.CallOption) (*modules_order.GetOrdersByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(modules_order.GetOrdersByUserResponse)
	err := c.cc.Invoke(ctx, OrderGRPCService_GetOrdersByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderGRPCServiceServer is the server API for OrderGRPCService service.
// All implementations must embed UnimplementedOrderGRPCServiceServer
// for forward compatibility.
type OrderGRPCServiceServer interface {
	CreateOrder(context.Context, *modules_order.CreateOrderRequest) (*modules_order.CreateOrderResponse, error)
	GetOrder(context.Context, *modules_order.GetOrderRequest) (*modules_order.GetOrderResponse, error)
	GetOrdersByUser(context.Context, *modules_order.GetOrdersByUserRequest) (*modules_order.GetOrdersByUserResponse, error)
	mustEmbedUnimplementedOrderGRPCServiceServer()
}

// UnimplementedOrderGRPCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderGRPCServiceServer struct{}

func (UnimplementedOrderGRPCServiceServer) CreateOrder(context.Context, *modules_order.CreateOrderRequest) (*modules_order.CreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderGRPCServiceServer) GetOrder(context.Context, *modules_order.GetOrderRequest) (*modules_order.GetOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderGRPCServiceServer) GetOrdersByUser(context.Context, *modules_order.GetOrdersByUserRequest) (*modules_order.GetOrdersByUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrdersByUser not implemented")
}
func (UnimplementedOrderGRPCServiceServer) mustEmbedUnimplementedOrderGRPCServiceServer() {}
func (UnimplementedOrderGRPCServiceServer) testEmbeddedByValue()                          {}

// UnsafeOrderGRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderGRPCServiceServer will
// result in compilation errors.
type UnsafeOrderGRPCServiceServer interface {
	mustEmbedUnimplementedOrderGRPCServiceServer()
}

func RegisterOrderGRPCServiceServer(s grpc.ServiceRegistrar, srv OrderGRPCServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderGRPCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderGRPCService_ServiceDesc, srv)
}

func _OrderGRPCService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(modules_order.CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderGRPCServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderGRPCService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderGRPCServiceServer).CreateOrder(ctx, req.(*modules_order.CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderGRPCService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(modules_order.GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderGRPCServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderGRPCService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderGRPCServiceServer).GetOrder(ctx, req.(*modules_order.GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderGRPCService_GetOrdersByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(modules_order.GetOrdersByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderGRPCServiceServer).GetOrdersByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderGRPCService_GetOrdersByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderGRPCServiceServer).GetOrdersByUser(ctx, req.(*modules_order.GetOrdersByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderGRPCService_ServiceDesc is the grpc.ServiceDesc for OrderGRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderGRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.order.OrderGRPCService",
	HandlerType: (*OrderGRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createOrder",
			Handler:    _OrderGRPCService_CreateOrder_Handler,
		},
		{
			MethodName: "getOrder",
			Handler:    _OrderGRPCService_GetOrder_Handler,
		},
		{
			MethodName: "getOrdersByUser",
			Handler:    _OrderGRPCService_GetOrdersByUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/order-service.proto",
}
