// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: services/order-service.proto

package services_order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	modules_order "order-service/go-proto/proto/modules.order"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_order_service_proto protoreflect.FileDescriptor

const file_services_order_service_proto_rawDesc = "" +
	"\n" +
	"\x1cservices/order-service.proto\x12\x0eservices.order\x1a\x13modules/order.proto2\x97\x02\n" +
	"\x10OrderGRPCService\x12T\n" +
	"\vcreateOrder\x12!.modules.order.CreateOrderRequest\x1a\".modules.order.CreateOrderResponse\x12K\n" +
	"\bgetOrder\x12\x1e.modules.order.GetOrderRequest\x1a\x1f.modules.order.GetOrderResponse\x12`\n" +
	"\x0fgetOrdersByUser\x12%.modules.order.GetOrdersByUserRequest\x1a&.modules.order.GetOrdersByUserResponseB-Z+order-service/go-proto/proto/services.orderb\x06proto3"

var file_services_order_service_proto_goTypes = []any{
	(*modules_order.CreateOrderRequest)(nil),      // 0: modules.order.CreateOrderRequest
	(*modules_order.GetOrderRequest)(nil),         // 1: modules.order.GetOrderRequest
	(*modules_order.GetOrdersByUserRequest)(nil),  // 2: modules.order.GetOrdersByUserRequest
	(*modules_order.CreateOrderResponse)(nil),     // 3: modules.order.CreateOrderResponse
	(*modules_order.GetOrderResponse)(nil),        // 4: modules.order.GetOrderResponse
	(*modules_order.GetOrdersByUserResponse)(nil), // 5: modules.order.GetOrdersByUserResponse
}
var file_services_order_service_proto_depIdxs = []int32{
	0, // 0: services.order.OrderGRPCService.createOrder:input_type -> modules.order.CreateOrderRequest
	1, // 1: services.order.OrderGRPCService.getOrder:input_type -> modules.order.GetOrderRequest
	2, // 2: services.order.OrderGRPCService.getOrdersByUser:input_type -> modules.order.GetOrdersByUserRequest
	3, // 3: services.order.OrderGRPCService.createOrder:output_type -> modules.order.CreateOrderResponse
	4, // 4: services.order.OrderGRPCService.getOrder:output_type -> modules.order.GetOrderResponse
	5, // 5: services.order.OrderGRPCService.getOrdersByUser:output_type -> modules.order.GetOrdersByUserResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_order_service_proto_init() }
func file_services_order_service_proto_init() {
	if File_services_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_order_service_proto_rawDesc), len(file_services_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_order_service_proto_goTypes,
		DependencyIndexes: file_services_order_service_proto_depIdxs,
	}.Build()
	File_services_order_service_proto = out.File
	file_services_order_service_proto_goTypes = nil
	file_services_order_service_proto_depIdxs = nil
}
